import React from 'react'

const Loading = () => {
    return (
        <div className='flex justify-center items-center text-center h-screen w-full'>
            <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 100 100"
                preserveAspectRatio="xMidYMid"
                // className='bg-blue-50'
                style={{
                    shapeRendering: "auto",
                    display: "block",
                }}
                width={50}
                height={50}
                xmlnsXlink="http://www.w3.org/1999/xlink"
            >
                <g>
                    <circle
                        cx={50}
                        cy={50}
                        fill="none"
                        stroke="#2a46cc"
                        strokeWidth={10}
                        r={35}
                        strokeDasharray="164.93361431346415 56.97787143782138"
                    >
                        <animateTransform
                            attributeName="transform"
                            type="rotate"
                            repeatCount="indefinite"
                            dur="1s"
                            values="0 50 50;360 50 50"
                            keyTimes="0;1"
                        />
                    </circle>
                    <g />
                </g>
                {/* [ldio] generated by https://loading.io */}
            </svg>
        </div>
    )
}

export default Loading